/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmReporteVentas.java
 *
 * Created on 10-jul-2012, 17:11:43
 */
package reportes;

import clases.clsCabecera;
import clases.clsPago;
import clases.clsReporte;
import clases.clsUtils;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CKaiser
 */
public class frmListPagos extends javax.swing.JInternalFrame {
    clsUtils objUtils = new clsUtils();
    clsPago objPago = new clsPago();
    MiModelo dtmData = new MiModelo();
    clsReporte objReporte = new clsReporte();
    Double totalEfectivo = 0.00;      
    /** Creates new form frmReporteVentas */
    public frmListPagos() {
        initComponents();
        
        dtmData.addColumn("N°");/*.setPreferredWidth(500)*/
        dtmData.addColumn("FECHA DEL PAGO");
        dtmData.addColumn("CLIENTE");
        dtmData.addColumn("VALOR DEL PAGO");
        dtmData.addColumn("USUARIO");       
        dtmData.addColumn("REFERENCIA");  
        dtmData.addColumn("REGISTRO");
        dtmData.addColumn("CODIGO");
        dtmData.addColumn("TIPO");
        
        colocarFechaActual();
                
        
        //ALINEAR COLUMNA
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.RIGHT);
        tblData.getColumnModel().getColumn(3).setCellRenderer(tcr);        
        
        tblData.setAutoCreateRowSorter(true);  
    }

    public void colocarFechaActual()
    {
        Date fechaActual = new Date();
        txtFechaInicio.setDate(fechaActual);
        txtFechaFin.setDate(fechaActual); 
        txtFechaInicioRegistro.setDate(fechaActual);
        txtFechaFinRegistro.setDate(fechaActual); 
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtFechaInicio = new com.toedter.calendar.JDateChooser();
        txtFechaFin = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        chkFechaPago = new javax.swing.JCheckBox();
        chkFechaRegistro = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        txtFechaInicioRegistro = new com.toedter.calendar.JDateChooser();
        txtFechaFinRegistro = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        chkNE = new javax.swing.JCheckBox();
        chkFacturas = new javax.swing.JCheckBox();
        chkVarios = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        btnImprimir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stinventario.STInventarioApp.class).getContext().getResourceMap(frmListPagos.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        txtFechaInicio.setDateFormatString(resourceMap.getString("txtFechaInicio.dateFormatString")); // NOI18N
        txtFechaInicio.setEnabled(false);
        txtFechaInicio.setName("txtFechaInicio"); // NOI18N
        txtFechaInicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtFechaInicioPropertyChange(evt);
            }
        });

        txtFechaFin.setDateFormatString(resourceMap.getString("txtFechaFin.dateFormatString")); // NOI18N
        txtFechaFin.setEnabled(false);
        txtFechaFin.setName("txtFechaFin"); // NOI18N
        txtFechaFin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtFechaFinPropertyChange(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        btnBuscar.setText(resourceMap.getString("btnBuscar.text")); // NOI18N
        btnBuscar.setName("btnBuscar"); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        chkFechaPago.setText(resourceMap.getString("chkFechaPago.text")); // NOI18N
        chkFechaPago.setName("chkFechaPago"); // NOI18N
        chkFechaPago.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkFechaPagoItemStateChanged(evt);
            }
        });

        chkFechaRegistro.setText(resourceMap.getString("chkFechaRegistro.text")); // NOI18N
        chkFechaRegistro.setName("chkFechaRegistro"); // NOI18N
        chkFechaRegistro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkFechaRegistroItemStateChanged(evt);
            }
        });

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        txtFechaInicioRegistro.setDateFormatString(resourceMap.getString("txtFechaInicioRegistro.dateFormatString")); // NOI18N
        txtFechaInicioRegistro.setEnabled(false);
        txtFechaInicioRegistro.setName("txtFechaInicioRegistro"); // NOI18N
        txtFechaInicioRegistro.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtFechaInicioRegistroPropertyChange(evt);
            }
        });

        txtFechaFinRegistro.setDateFormatString(resourceMap.getString("txtFechaFinRegistro.dateFormatString")); // NOI18N
        txtFechaFinRegistro.setEnabled(false);
        txtFechaFinRegistro.setName("txtFechaFinRegistro"); // NOI18N
        txtFechaFinRegistro.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtFechaFinRegistroPropertyChange(evt);
            }
        });

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        chkNE.setSelected(true);
        chkNE.setText(resourceMap.getString("chkNE.text")); // NOI18N
        chkNE.setName("chkNE"); // NOI18N

        chkFacturas.setSelected(true);
        chkFacturas.setText(resourceMap.getString("chkFacturas.text")); // NOI18N
        chkFacturas.setName("chkFacturas"); // NOI18N

        chkVarios.setSelected(true);
        chkVarios.setText(resourceMap.getString("chkVarios.text")); // NOI18N
        chkVarios.setName("chkVarios"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkFechaPago)
                            .addComponent(chkFechaRegistro))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chkNE)
                                .addGap(18, 18, 18)
                                .addComponent(chkFacturas)
                                .addGap(18, 18, 18)
                                .addComponent(chkVarios))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtFechaInicioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtFechaFinRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(chkFechaPago))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFechaFinRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txtFechaInicioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkFechaRegistro)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkNE)
                    .addComponent(chkFacturas)
                    .addComponent(chkVarios)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setName("jPanel2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblData.setModel(dtmData);
        tblData.setName("tblData"); // NOI18N
        jScrollPane1.setViewportView(tblData);

        btnImprimir.setIcon(resourceMap.getIcon("btnImprimir.icon")); // NOI18N
        btnImprimir.setText(resourceMap.getString("btnImprimir.text")); // NOI18N
        btnImprimir.setName("btnImprimir"); // NOI18N
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        txtTotal.setFont(resourceMap.getFont("txtTotal.font")); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotal.setText(resourceMap.getString("txtTotal.text")); // NOI18N
        txtTotal.setName("txtTotal"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnImprimir)
                        .addGap(472, 472, 472)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnImprimir)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtFechaInicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtFechaInicioPropertyChange
    //buscar_informacion();
}//GEN-LAST:event_txtFechaInicioPropertyChange

private void txtFechaFinPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtFechaFinPropertyChange
    //buscar_informacion();
}//GEN-LAST:event_txtFechaFinPropertyChange

private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    totalEfectivo=0.00;
    buscar_informacion();
    
}//GEN-LAST:event_btnBuscarActionPerformed
    public void llenarData(ArrayList<clsPago> dataPago, String tipo)
    {
        //Double totalEfectivo = 0.00;        
        
        DecimalFormat df1 = new DecimalFormat("##0.00"); 
       
            int maxData = dataPago.size();  
            String fecha_realizada = "";
            String fecha_registro = "";

            for(int i=0; i<maxData; i++)
            {                    
                 //fecha_realizada = dataPago.get(i).getFechaPago().substring(0, 16);    
                 fecha_realizada = dataPago.get(i).getFechaPago().substring(0, 16);    
                 if( dataPago.get(i).getFechaRegistro()==null)
                 {
                     fecha_registro="";
                 }
                 else
                     fecha_registro = dataPago.get(i).getFechaRegistro().substring(0, 16);    
                 Object[] nuevaFila = {  i+1,                          
                                        fecha_realizada,
                                        dataPago.get(i).getNombreCliente(),
                                        "$ " + df1.format(dataPago.get(i).getValor()), 
                                        dataPago.get(i).getNombreUsuario(),   
                                        dataPago.get(i).getReferencia(),
                                        fecha_registro,
                                        dataPago.get(i).getIdPago(),
                                        tipo
                 };        

                 totalEfectivo = totalEfectivo + dataPago.get(i).getValor();             
                 dtmData.addRow(nuevaFila); 
            }         
            txtTotal.setText("" + (objUtils.redondear(totalEfectivo)));     
        
    }
     
    public void buscar_informacion()
    {
        objUtils.vaciarTabla(dtmData);        

        String fechaInicio = "";
        String fechaFin = "";
        
        DateFormat df1 = new SimpleDateFormat("yyyy-MM-dd");
        
            
        if(this.chkFechaPago.isSelected())
        {   
            Date date1 = txtFechaInicio.getDate();
            fechaInicio = df1.format(date1);

            Date date2 = txtFechaFin.getDate();
            fechaFin = df1.format(date2);
        
            if(chkNE.isSelected())
            {  
                /*ArrayList<clsPago> dataPago = objPago.consultaDataPagosFecha(fechaInicio, fechaFin); 
                if(dataPago.isEmpty())
                {
                    JOptionPane.showMessageDialog(this, "No existen datos", "Atención!", JOptionPane.WARNING_MESSAGE);
                }
                else
                {
                    llenarData(dataPago, "NE");
                }*/
                ArrayList<clsPago> dataPago = objPago.consultaDataPagosFecha(fechaInicio, fechaFin); 
                llenarData(dataPago, "NE");
            }       
            if(chkFacturas.isSelected())
            {  
                ArrayList<clsPago> dataPago2 = objPago.consultaDataPagosFacturaFecha(fechaInicio, fechaFin);                    
                llenarData(dataPago2, "FACTURA");    
            }     
            if(chkVarios.isSelected())
            {  
                ArrayList<clsPago> dataPago3 = objPago.consultaDataPagosOtrosRegistroFecha(fechaInicio, fechaFin);                     
                llenarData(dataPago3, "OTROS");    
            }   
            
            
        }   
        else if (this.chkFechaRegistro.isSelected())
        {
            Date date1 = txtFechaInicioRegistro.getDate();
            fechaInicio = df1.format(date1);

            Date date2 = txtFechaFinRegistro.getDate();
            fechaFin = df1.format(date2);
            
            if(chkNE.isSelected())
            {  
                ArrayList<clsPago> dataPago = objPago.consultaDataPagosRegistroFecha(fechaInicio, fechaFin); 
                llenarData(dataPago, "NE");
            }       
            if(chkFacturas.isSelected())
            {  
                ArrayList<clsPago> dataPago2 = objPago.consultaDataPagosFacturaRegistroFecha(fechaInicio, fechaFin);                    
                llenarData(dataPago2, "FACTURA");    
            }     
            if(chkVarios.isSelected())
            {  
                ArrayList<clsPago> dataPago3 = objPago.consultaDataPagosOtrosRegistroFecha(fechaInicio, fechaFin);                     
                llenarData(dataPago3, "OTROS");    
            }   
            
        }
        else
        {
            if(chkNE.isSelected())
            {  
                ArrayList<clsPago> dataPago = objPago.consultaDataPagos();                      
                llenarData(dataPago, "NE");    
            }       
            if(chkFacturas.isSelected())
            {  
                ArrayList<clsPago> dataPago2 = objPago.consultaDataPagosFactura();                      
                llenarData(dataPago2, "FACTURA");    
            }     
            if(chkVarios.isSelected())
            {  
                ArrayList<clsPago> dataPago3 = objPago.consultaDataPagosOtros();                      
                llenarData(dataPago3, "OTROS");    
            }     
        }
    }  
    
private void chkFechaPagoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkFechaPagoItemStateChanged
    colocarFechaActual();
    if(this.chkFechaPago.isSelected())
    {
        chkFechaRegistro.setSelected(false);
        txtFechaInicio.setEnabled(true);  
        txtFechaFin.setEnabled(true);  
        
        txtFechaInicioRegistro.setEnabled(false);  
        txtFechaFinRegistro.setEnabled(false);    
    }
    else
    {
        txtFechaInicio.setEnabled(false);  
        txtFechaFin.setEnabled(false);        
    } 
}//GEN-LAST:event_chkFechaPagoItemStateChanged

    public class MiModelo extends DefaultTableModel
    {
            @Override
       public boolean isCellEditable (int row, int column)
       {
           // Aquí devolvemos true o false según queramos que una celda
           // identificada por fila,columna (row,column), sea o no editable
          /* if (column == 3)
              return true;*/
           
           return false;
       }
    } 

private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
    if(this.chkFechaPago.isSelected())
    {
        Date date1 = txtFechaInicio.getDate();
        //fechaInicio = df1.format(date1);

        Date date2 = txtFechaFin.getDate();
        //fechaFin = df1.format(date2);

        /*ArrayList<clsCompras> dataCompras = objCompras.consultaDataComprasRangoRegistro(fechaInicio, fechaFin); 
        llenarData(dataCompras);*/
        objReporte.ejecutarReporte2ParametrosDate(date1, date2, "rptPagosTotalesFecha");
    }
    else if (this.chkFechaRegistro.isSelected())
    {
        Date date1 = txtFechaInicioRegistro.getDate();
        Date date2 = txtFechaFinRegistro.getDate();
        
        objReporte.ejecutarReporte2ParametrosDate(date1, date2, "rptPagosTotalesFechaRegistro");
    }        
    else
    {
        objReporte.ejecutarReporte("rptPagosTotales"); 
    }
}//GEN-LAST:event_btnImprimirActionPerformed

private void chkFechaRegistroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkFechaRegistroItemStateChanged
    colocarFechaActual();
    if(this.chkFechaRegistro.isSelected())
    {
        chkFechaPago.setSelected(false);
        txtFechaInicioRegistro.setEnabled(true);  
        txtFechaFinRegistro.setEnabled(true);  
        
        txtFechaInicio.setEnabled(false);  
        txtFechaFin.setEnabled(false);    
    }
    else
    {
        txtFechaInicioRegistro.setEnabled(false);  
        txtFechaFinRegistro.setEnabled(false);        
    } 
}//GEN-LAST:event_chkFechaRegistroItemStateChanged

private void txtFechaInicioRegistroPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtFechaInicioRegistroPropertyChange
// TODO add your handling code here:
}//GEN-LAST:event_txtFechaInicioRegistroPropertyChange

private void txtFechaFinRegistroPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtFechaFinRegistroPropertyChange
// TODO add your handling code here:
}//GEN-LAST:event_txtFechaFinRegistroPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JCheckBox chkFacturas;
    private javax.swing.JCheckBox chkFechaPago;
    private javax.swing.JCheckBox chkFechaRegistro;
    private javax.swing.JCheckBox chkNE;
    private javax.swing.JCheckBox chkVarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblData;
    private com.toedter.calendar.JDateChooser txtFechaFin;
    private com.toedter.calendar.JDateChooser txtFechaFinRegistro;
    private com.toedter.calendar.JDateChooser txtFechaInicio;
    private com.toedter.calendar.JDateChooser txtFechaInicioRegistro;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
