/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package clientes;

import clases.clsCliente;
import clases.clsPago;
import clases.clsUtils;
import java.awt.Dimension;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import stinventario.frmPrincipal;

/**
 *
 * @author User
 */
public class frmReporteCartera extends javax.swing.JInternalFrame {
    MiModelo dtmData = new MiModelo();
    clsUtils objUtils = new clsUtils();
    clsCliente objCliente = new clsCliente();
    /**
     * Creates new form frmReporteCartera
     */
    public frmReporteCartera() {
        initComponents();
        
        dtmData.addColumn("N°");/*.setPreferredWidth(500)*/
        dtmData.addColumn("CEDULA");
        dtmData.addColumn("NOMBRE");
        dtmData.addColumn("RECINTO");
        dtmData.addColumn("DIRECCION");
        dtmData.addColumn("TELEFONO");       
        dtmData.addColumn("FECHA CREDITO");  
        dtmData.addColumn("VALOR");
        dtmData.addColumn("PLAZO CREDITO");
        dtmData.addColumn("DIAS DE MORA");
        dtmData.addColumn("VALOR PENDIENTE");
        dtmData.addColumn("ULTIMA OBSERVACION");
        dtmData.addColumn("IDCABECERA");       
                
        //objUtils.setOcultarColumnasJTable(this.tblData, new int[]{12});  
        //ALINEAR COLUMNA
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.RIGHT);
        tblData.getColumnModel().getColumn(3).setCellRenderer(tcr);        
        
        tblData.setAutoCreateRowSorter(true); 
        
        objUtils.vaciarTabla(dtmData);  
        
        buscar_informacion();
    }
    
    public void buscar_informacion()
    {
         ArrayList<clsCliente> dataCliente = objCliente.consultarDataClienteCartera();
                    if(!dataCliente.isEmpty())
                    {
                        llenarData(dataCliente);
                    }
    }
    
    public void llenarData(ArrayList<clsCliente> dataCliente)
    {
        //Double totalEfectivo = 0.00;        
        
        DecimalFormat df1 = new DecimalFormat("##0.00"); 
       
            int maxData = dataCliente.size();  
            String fecha_realizada = "";
            String fecha_registro = "";

            for(int i=0; i<maxData; i++)
            {                    
                
        Object[] nuevaFila = {  i+1,                          
                                        dataCliente.get(i).getCedula(),
                                        dataCliente.get(i).getNameCompleto(),
                                        dataCliente.get(i).getDescripcionRecinto(), 
                                        dataCliente.get(i).getDireccion(),   
                                        dataCliente.get(i).getTlfCelular(),
                                        dataCliente.get(i).getFecha(),
                                        dataCliente.get(i).getDeudaTotal(),
                                        dataCliente.get(i).getDescripcionPlazo(),
                                        dataCliente.get(i).getDiferencia(),
                                        dataCliente.get(i).getValorActual(),
                                        "",
                                        dataCliente.get(i).getIdCabeceraMovi()
                 };                    
                 

                 //totalEfectivo = totalEfectivo + dataPago.get(i).getValor();             
                 dtmData.addRow(nuevaFila); 
            }         
            //txtTotal.setText("" + (objUtils.redondear(totalEfectivo)));     
        
    }
    
    public class MiModelo extends DefaultTableModel
    {
            @Override
       public boolean isCellEditable (int row, int column)
       {
           // Aquí devolvemos true o false según queramos que una celda
           // identificada por fila,columna (row,column), sea o no editable
          /* if (column == 3)
              return true;*/
           
           return false;
       }
    } 
    
    public static void mostrarJInternalCentrado(javax.swing.JInternalFrame formulario)
    {
        Dimension desktopSize = frmPrincipal.jDesktopPane1.getSize();
        Dimension jInternalFrameSize = formulario.getSize();
        formulario.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
        (desktopSize.height- jInternalFrameSize.height)/2);

        frmPrincipal.jDesktopPane1.add(formulario);
        formulario.show(); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblData.setModel(dtmData);
        tblData.setName("tblData"); // NOI18N
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int fila = tblData.rowAtPoint(evt.getPoint());
        int columna = tblData.columnAtPoint(evt.getPoint());
        /*int columna = 3;*/
        /*if ((fila > -1) && (columna > -1))*/
        int i = tblData.getSelectedRow();
        int idCabecera = Integer.parseInt("" + tblData.getValueAt(i, 12));
        String nombre = "" + tblData.getValueAt(i, 2);
        
        if (columna == 11)
        {
            frmComentario formulario = new frmComentario(idCabecera, nombre);
            mostrarJInternalCentrado(formulario);  
            //dispose();
        }
        
    }//GEN-LAST:event_tblDataMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables
}
