/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package transferencias;

import clases.clsCompras;
import clases.clsUtils;
import java.util.ArrayList;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class frmPendientes extends javax.swing.JInternalFrame {
    MiModelo dtmData = new MiModelo();
    clsUtils objUtils = new clsUtils();
    clsCompras objCompras = new clsCompras();
    /**
     * Creates new form frmPendientes
     */
    public frmPendientes() {
        initComponents();
        
        dtmData.addColumn("id");
        dtmData.addColumn("N°");/*.setPreferredWidth(500)*/
        dtmData.addColumn("CODIGO");
        dtmData.addColumn("CLIENTE");
        dtmData.addColumn("ESTADO");
        dtmData.addColumn("MODIFICAR");
        dtmData.addColumn("CONFIRMAR");
        dtmData.addColumn("FECHA CREACION");
        dtmData.addColumn("FECHA CONFIRMACION");
        dtmData.addColumn("ID");
        dtmData.addColumn("TOTAL");
        dtmData.addColumn("TIPO");
        //dtmData.addColumn("Valor");
        //dtmData.addColumn("idCabeceraMovi");
        //ALINEAR COLUMNA
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.RIGHT);
        tblData.getColumnModel().getColumn(10).setCellRenderer(tcr);
        
        //OCULTAR
        objUtils.setOcultarColumnasJTable(this.tblData, new int[]{0});
        
        ArrayList<clsCompras> dataCompras = objCompras.consultaDataNotasEntrega(); 
        llenarData(dataCompras);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblData.setModel(dtmData);
        tblData.setName("tblData"); // NOI18N
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int fila = tblData.rowAtPoint(evt.getPoint());
        int columna = tblData.columnAtPoint(evt.getPoint());
        /*int columna = 3;*/
        /*if ((fila > -1) && (columna > -1))*/
        int i = tblData.getSelectedRow();
        int idCabecera = Integer.parseInt(""+tblData.getValueAt(i, 0));
        System.out.println("x:" + idCabecera + " " + fila + " " + columna);
        //objReporte.ejecutarReporteParametroInt(idCabecera, "rptPagosFactura");
        /*frmComprasShow ventana = new frmComprasShow(null, true, idCabecera);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);*/
        if(tblData.getValueAt(i, 4).equals("CONFIRMADA"))
        {
           /*frmFactHistoShow ventana = new frmFactHistoShow(null, true, idCabecera);
            ventana.setLocationRelativeTo(null);
            ventana.setVisible(true);*/
        }
        else
        {
            if (columna == 6)
            {
                /*frmNotasEntregaConfirmar formulario = new frmNotasEntregaConfirmar(idCabecera);
                mostrarJInternalCentrado(formulario);
                dispose();*/
            }

            if (columna == 5)
            {
                /*frmNotasEntregaModificar formulario = new frmNotasEntregaModificar(idCabecera);
                mostrarJInternalCentrado(formulario);
                dispose();*/
            }
        }
    }//GEN-LAST:event_tblDataMouseClicked

    public class MiModelo extends DefaultTableModel
    {
            @Override
       public boolean isCellEditable (int row, int column)
       {
           // Aquí devolvemos true o false según queramos que una celda
           // identificada por fila,columna (row,column), sea o no editable
          /* if (column == 3)
              return true;*/
           
           return false;
       }
    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables
}
